services:
  app1:
    #environment:
      #- ISC_DATA_DIRECTORY=/dur/config
    ports:
      - '21772:1972'
      - '22773:52773'
    hostname: app1
    container_name: app1
    image: containers.intersystems.com/intersystems/iris:2023.3
    init: true
    restart: on-failure
    volumes:
      - ./app1sys:/dur
      - ./license:/license
      - ./logsApp2:/logs
      - ./shared:/shared
    command: --check-caps false --key /license/iris.key
  app2:
    #environment:
      #- ISC_DATA_DIRECTORY=/dur/config
    ports:
      - '31772:1972'
      - '32773:52773'
    hostname: app2
    container_name: app2
    image: containers.intersystems.com/intersystems/iris:2023.3
    init: true
    restart: on-failure
    volumes:
      - ./app2sys:/dur
      - ./license:/license
      - ./logsApp1:/logs
      - ./shared:/shared
    command: --check-caps false --key /license/iris.key

  irisM1:
    #environment:
      #- ISC_DATA_DIRECTORY=/dur/config
    ports:
      - '41772:1972'
      - '42773:52773'
    expose:
      - '2188'
    hostname: irisM1
    container_name: irisM1
    image: containers.intersystems.com/intersystems/iris:2023.3
    init: true
    restart: on-failure
    volumes:
      #- ./m1sys:/dur
      - ./license:/license
      - ./logsM1:/logs
      - ./shared:/shared
    command: --before "/home/irisowner/irissys/startISCAgent.sh 2188" --check-caps false --key /license/iris.key
  
volumes:
  m1sys: ~
  app1sys: ~
  app2sys: ~
#networks:
#  default:
#    external:
#      name: sam-100115-unix_default