version: '3.7'
services:
  irisM1:
    environment:
      - ISC_DATA_DIRECTORY=/dur/config
      #This merges from the cpf containing the mirror config and the IRIS password 
      - ISC_CPF_MERGE_FILE=/shared/irisM1Merge.cpf
    ports:
      - '21773:1972'
      - '22773:52773'
    expose:
      - '2188'
    hostname: irisM1
    #image: containers.intersystems.com/intersystems/iris:2021.1.0.215.0
    image: containers.intersystems.com/intersystems/iris:2022.1.0.209.0
    init: true
    restart: on-failure
    volumes:
      - ./m1sys:/dur
      - ./license:/license
      - ./logsM1:/logs
      - ./shared:/shared
    #command: --before "/home/irisowner/irissys/startISCAgent.sh 2188" --key /license/iris.key
    command: --key /license/iris.key --check-caps false
  irisM2:
    environment:
      - ISC_DATA_DIRECTORY=/dur/config
      #This merges from the cpf containing the mirror config and the IRIS password 
      - ISC_CPF_MERGE_FILE=/shared/irisM2Merge.cpf
    ports:
      - '31772:1972'
      - '32773:52773'
    expose:
      - '2188'
    hostname: irisM2        
    #image: containers.intersystems.com/intersystems/iris:2021.1.0.215.0
    image: containers.intersystems.com/intersystems/iris:2022.1.0.209.0
    init: true
    restart: on-failure
    volumes:
      - ./m2sys:/dur
      - ./license:/license
      - ./logsM2:/logs
      - ./shared:/shared
    #command: --before "/home/irisowner/irissys/startISCAgent.sh 2188" 
    command: --key /license/iris.key --check-caps false 
  arbiter:
    init: true
    hostname: arbiter
    #image: containers.intersystems.com/intersystems/arbiter:2021.1.0.215.0
    image: containers.intersystems.com/intersystems/arbiter:2022.1.0.209.0
    restart: on-failure
    expose:
      - '2188'
    command: 
      - /usr/local/etc/irissys/startISCAgent.sh 2188
  webserver:
      hostname: webserver
      #image: containers.intersystems.com/intersystems/webgateway:2021.1.0.215.0
      image: containers.intersystems.com/intersystems/webgateway:2022.1.0.209.0
      init: true
      restart: on-failure
      ports:
        - '21080:80'
      volumes:
        - ./webgatewayconfig:/config.d
      environment:
        - ISC_DATA_DIRECTORY=/config.d
      command: 
        - /bin/bash -c "/configHttpd.sh && apache2ctl start"
volumes:
  m1sys: ~
  m2sys: ~
#networks:
#    default:
#      external:
#        name: sam-100115-unix_default